// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Rcpp_rexp1
NumericVector Rcpp_rexp1(R_xlen_t n, double rate);
RcppExport SEXP _RcppRNG_Rcpp_rexp1(SEXP nSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< R_xlen_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_rexp1(n, rate));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_rexp2
NumericVector Rcpp_rexp2(R_xlen_t n, double rate);
RcppExport SEXP _RcppRNG_Rcpp_rexp2(SEXP nSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< R_xlen_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_rexp2(n, rate));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_rexp3
NumericVector Rcpp_rexp3(R_xlen_t n, double rate);
RcppExport SEXP _RcppRNG_Rcpp_rexp3(SEXP nSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< R_xlen_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_rexp3(n, rate));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_rexp4
NumericVector Rcpp_rexp4(R_xlen_t n, double rate);
RcppExport SEXP _RcppRNG_Rcpp_rexp4(SEXP nSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< R_xlen_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_rexp4(n, rate));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_rexp5
NumericVector Rcpp_rexp5(R_xlen_t n, double rate);
RcppExport SEXP _RcppRNG_Rcpp_rexp5(SEXP nSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< R_xlen_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_rexp5(n, rate));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppRNG_Rcpp_rexp1", (DL_FUNC) &_RcppRNG_Rcpp_rexp1, 2},
    {"_RcppRNG_Rcpp_rexp2", (DL_FUNC) &_RcppRNG_Rcpp_rexp2, 2},
    {"_RcppRNG_Rcpp_rexp3", (DL_FUNC) &_RcppRNG_Rcpp_rexp3, 2},
    {"_RcppRNG_Rcpp_rexp4", (DL_FUNC) &_RcppRNG_Rcpp_rexp4, 2},
    {"_RcppRNG_Rcpp_rexp5", (DL_FUNC) &_RcppRNG_Rcpp_rexp5, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppRNG(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
