# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' \code{rexp} implementations in Rcpp for benchmarking
#'
#' These functions serve no real purpose except demonstrating
#' how to use the RNG Generators and providing some functions
#' for benchmarks.
#'
#' @inheritParams stats::rexp
#'
#' @name rexp-Rcpp
NULL

#' @rdname rexp-Rcpp
#'
#' @export
Rcpp_rexp1 <- function(n, rate = 1.) {
    .Call(`_RcppRNG_Rcpp_rexp1`, n, rate)
}

#' @rdname rexp-Rcpp
#'
#' @export
Rcpp_rexp2 <- function(n, rate = 1.) {
    .Call(`_RcppRNG_Rcpp_rexp2`, n, rate)
}

#' @rdname rexp-Rcpp
#'
#' @export
Rcpp_rexp3 <- function(n, rate = 1.) {
    .Call(`_RcppRNG_Rcpp_rexp3`, n, rate)
}

#' @rdname rexp-Rcpp
#'
#' @export
Rcpp_rexp4 <- function(n, rate = 1.) {
    .Call(`_RcppRNG_Rcpp_rexp4`, n, rate)
}

#' @rdname rexp-Rcpp
#'
#' @export
Rcpp_rexp5 <- function(n, rate = 1.) {
    .Call(`_RcppRNG_Rcpp_rexp5`, n, rate)
}

