# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Set the seed for the DQRNG
#'
#' Original in \url{https://github.com/daqana/dqrng/blob/master/src/dqrng.cpp}
#'
#' @inheritParams dqrng::dqset.seed
#'
#' @seealso \code{\link[dqrng]{dqset.seed}}
#' @export
dqset_seed <- function(seed, stream = NULL) {
    invisible(.Call(`_RcppRNG_dqset_seed`, seed, stream))
}

#' Choose RNGkind for DQRNG
#'
#' Original in \url{https://github.com/daqana/dqrng/blob/master/src/dqrng.cpp}
#'
#' @inheritParams dqrng::dqRNGkind
#'
#' @seealso \code{\link[dqrng]{dqRNGkind}}
#'
#' @export
dqRNGkind <- function(kind, normal_kind = "ignored") {
    invisible(.Call(`_RcppRNG_dqRNGkind`, kind, normal_kind))
}

#' Alternatives for \code{rexp}
#'
#' @param n Number of samples
#' @param rate Rate parameter
#'
#' @name rexp-alternative
#' @export
Rcpp_rexp_RNGScope <- function(n, rate = 1.) {
    .Call(`_RcppRNG_Rcpp_rexp_RNGScope`, n, rate)
}

#' @rdname rexp-alternative
#' @export
Rcpp_rexp_RCPPRNG <- function(n, rate = 1.) {
    .Call(`_RcppRNG_Rcpp_rexp_RCPPRNG`, n, rate)
}

#' @rdname rexp-alternative
#' @export
Rcpp_rexp_DQRNG <- function(n, rate = 1.) {
    .Call(`_RcppRNG_Rcpp_rexp_DQRNG`, n, rate)
}

